//go:build go1.22

// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	models "github.com/InWheelOrg/inwheel-api/pkg/models"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for AccessibilityLevel.
const (
	Good    AccessibilityLevel = "good"
	Limited AccessibilityLevel = "limited"
	No      AccessibilityLevel = "no"
)

// Valid indicates whether the value is a known member of the AccessibilityLevel enum.
func (e AccessibilityLevel) Valid() bool {
	switch e {
	case Good:
		return true
	case Limited:
		return true
	case No:
		return true
	default:
		return false
	}
}

// Defines values for Category.
const (
	Airport      Category = "airport"
	Cafe         Category = "cafe"
	Entrance     Category = "entrance"
	Mall         Category = "mall"
	Other        Category = "other"
	Parking      Category = "parking"
	Restaurant   Category = "restaurant"
	Shop         Category = "shop"
	Toilet       Category = "toilet"
	TrainStation Category = "train_station"
)

// Valid indicates whether the value is a known member of the Category enum.
func (e Category) Valid() bool {
	switch e {
	case Airport:
		return true
	case Cafe:
		return true
	case Entrance:
		return true
	case Mall:
		return true
	case Other:
		return true
	case Parking:
		return true
	case Restaurant:
		return true
	case Shop:
		return true
	case Toilet:
		return true
	case TrainStation:
		return true
	default:
		return false
	}
}

// Defines values for DoorType.
const (
	Automatic DoorType = "automatic"
	Manual    DoorType = "manual"
	None      DoorType = "none"
	Revolving DoorType = "revolving"
)

// Valid indicates whether the value is a known member of the DoorType enum.
func (e DoorType) Valid() bool {
	switch e {
	case Automatic:
		return true
	case Manual:
		return true
	case None:
		return true
	case Revolving:
		return true
	default:
		return false
	}
}

// Defines values for OSMType.
const (
	Node     OSMType = "node"
	Relation OSMType = "relation"
	Way      OSMType = "way"
)

// Valid indicates whether the value is a known member of the OSMType enum.
func (e OSMType) Valid() bool {
	switch e {
	case Node:
		return true
	case Relation:
		return true
	case Way:
		return true
	default:
		return false
	}
}

// Defines values for PlaceStatus.
const (
	Active     PlaceStatus = "active"
	Closed     PlaceStatus = "closed"
	OsmRemoved PlaceStatus = "osm_removed"
)

// Valid indicates whether the value is a known member of the PlaceStatus enum.
func (e PlaceStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case OsmRemoved:
		return true
	default:
		return false
	}
}

// Defines values for SurfaceType.
const (
	Asphalt      SurfaceType = "asphalt"
	Carpet       SurfaceType = "carpet"
	Cobblestone  SurfaceType = "cobblestone"
	Concrete     SurfaceType = "concrete"
	Gravel       SurfaceType = "gravel"
	PavingStones SurfaceType = "paving_stones"
	Tiles        SurfaceType = "tiles"
	Wood         SurfaceType = "wood"
)

// Valid indicates whether the value is a known member of the SurfaceType enum.
func (e SurfaceType) Valid() bool {
	switch e {
	case Asphalt:
		return true
	case Carpet:
		return true
	case Cobblestone:
		return true
	case Concrete:
		return true
	case Gravel:
		return true
	case PavingStones:
		return true
	case Tiles:
		return true
	case Wood:
		return true
	default:
		return false
	}
}

// AccessibilityLevel defines model for AccessibilityLevel.
type AccessibilityLevel string

// AccessibilityProfile defines model for AccessibilityProfile.
type AccessibilityProfile = models.AccessibilityProfile

// Category defines model for Category.
type Category string

// DoorProps defines model for DoorProps.
type DoorProps = models.DoorProps

// DoorType defines model for DoorType.
type DoorType string

// ElevatorProps defines model for ElevatorProps.
type ElevatorProps = models.ElevatorProps

// EntranceProps defines model for EntranceProps.
type EntranceProps = models.EntranceProps

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExternalRef defines model for ExternalRef.
type ExternalRef = models.ExternalRef

// FieldError defines model for FieldError.
type FieldError struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// OSMType defines model for OSMType.
type OSMType string

// ParkingProps defines model for ParkingProps.
type ParkingProps = models.ParkingProps

// PathwayProps defines model for PathwayProps.
type PathwayProps = models.PathwayProps

// Place defines model for Place.
type Place = models.Place

// PlacePage defines model for PlacePage.
type PlacePage struct {
	Data []Place `json:"data"`

	// NextCursor Opaque cursor for the next page. Absent when this is the last page. Re-send all filter params unchanged on each subsequent request.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PlaceStatus defines model for PlaceStatus.
type PlaceStatus string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// ApiKey Raw API key shown exactly once. Store it securely.
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
}

// RestroomProps defines model for RestroomProps.
type RestroomProps = models.RestroomProps

// SourceReport defines model for SourceReport.
type SourceReport struct {
	RecordedAt time.Time `json:"recorded_at"`
	Source     string    `json:"source"`
	Value      string    `json:"value"`
}

// SurfaceType defines model for SurfaceType.
type SurfaceType string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Error  string       `json:"error"`
	Fields []FieldError `json:"fields"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// ListPlacesParams defines parameters for ListPlaces.
type ListPlacesParams struct {
	Limit  *int     `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Q      *string  `form:"q,omitempty" json:"q,omitempty"`
	Lng    *float64 `form:"lng,omitempty" json:"lng,omitempty"`
	Lat    *float64 `form:"lat,omitempty" json:"lat,omitempty"`
	Radius *float64 `form:"radius,omitempty" json:"radius,omitempty"`
	MinLng *float64 `form:"min_lng,omitempty" json:"min_lng,omitempty"`
	MinLat *float64 `form:"min_lat,omitempty" json:"min_lat,omitempty"`
	MaxLng *float64 `form:"max_lng,omitempty" json:"max_lng,omitempty"`
	MaxLat *float64 `form:"max_lat,omitempty" json:"max_lat,omitempty"`
}

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreatePlaceJSONRequestBody defines body for CreatePlace for application/json ContentType.
type CreatePlaceJSONRequestBody = Place

// PatchPlaceAccessibilityJSONRequestBody defines body for PatchPlaceAccessibility for application/json ContentType.
type PatchPlaceAccessibilityJSONRequestBody = AccessibilityProfile

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Revoke the authenticated API key
	// (DELETE /auth/keys)
	RevokeKey(w http.ResponseWriter, r *http.Request)
	// Register and receive an API key
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// List places with cursor-based pagination
	// (GET /places)
	ListPlaces(w http.ResponseWriter, r *http.Request, params ListPlacesParams)
	// Create a place
	// (POST /places)
	CreatePlace(w http.ResponseWriter, r *http.Request)
	// Get a single place
	// (GET /places/{id})
	GetPlace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update or create an accessibility profile
	// (PATCH /places/{id}/accessibility)
	PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "radius"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lng", r.URL.Query(), &params.MinLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lat", r.URL.Query(), &params.MinLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lng", r.URL.Query(), &params.MaxLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lat", r.URL.Query(), &params.MaxLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_lat", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlace operation middleware
func (siw *ServerInterfaceWrapper) CreatePlace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlace operation middleware
func (siw *ServerInterfaceWrapper) GetPlace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchPlaceAccessibility operation middleware
func (siw *ServerInterfaceWrapper) PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchPlaceAccessibility(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/auth/keys", wrapper.RevokeKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/places", wrapper.ListPlaces)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/places", wrapper.CreatePlace)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/places/{id}", wrapper.GetPlace)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/places/{id}/accessibility", wrapper.PatchPlaceAccessibility)

	return m
}

type RevokeKeyRequestObject struct {
}

type RevokeKeyResponseObject interface {
	VisitRevokeKeyResponse(w http.ResponseWriter) error
}

type RevokeKey204Response struct {
}

func (response RevokeKey204Response) VisitRevokeKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeKey401JSONResponse ErrorResponse

func (response RevokeKey401JSONResponse) VisitRevokeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse RegisterResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse ValidationError

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register429JSONResponse ErrorResponse

func (response Register429JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlacesRequestObject struct {
	Params ListPlacesParams
}

type ListPlacesResponseObject interface {
	VisitListPlacesResponse(w http.ResponseWriter) error
}

type ListPlaces200JSONResponse PlacePage

func (response ListPlaces200JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces400JSONResponse ValidationError

func (response ListPlaces400JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaceRequestObject struct {
	Body *CreatePlaceJSONRequestBody
}

type CreatePlaceResponseObject interface {
	VisitCreatePlaceResponse(w http.ResponseWriter) error
}

type CreatePlace201JSONResponse Place

func (response CreatePlace201JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace400JSONResponse ValidationError

func (response CreatePlace400JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace401JSONResponse ErrorResponse

func (response CreatePlace401JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaceRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPlaceResponseObject interface {
	VisitGetPlaceResponse(w http.ResponseWriter) error
}

type GetPlace200JSONResponse Place

func (response GetPlace200JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlace400JSONResponse ValidationError

func (response GetPlace400JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlace404JSONResponse ErrorResponse

func (response GetPlace404JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibilityRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchPlaceAccessibilityJSONRequestBody
}

type PatchPlaceAccessibilityResponseObject interface {
	VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error
}

type PatchPlaceAccessibility200JSONResponse AccessibilityProfile

func (response PatchPlaceAccessibility200JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility400JSONResponse ValidationError

func (response PatchPlaceAccessibility400JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility401JSONResponse ErrorResponse

func (response PatchPlaceAccessibility401JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility404JSONResponse ErrorResponse

func (response PatchPlaceAccessibility404JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Revoke the authenticated API key
	// (DELETE /auth/keys)
	RevokeKey(ctx context.Context, request RevokeKeyRequestObject) (RevokeKeyResponseObject, error)
	// Register and receive an API key
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// List places with cursor-based pagination
	// (GET /places)
	ListPlaces(ctx context.Context, request ListPlacesRequestObject) (ListPlacesResponseObject, error)
	// Create a place
	// (POST /places)
	CreatePlace(ctx context.Context, request CreatePlaceRequestObject) (CreatePlaceResponseObject, error)
	// Get a single place
	// (GET /places/{id})
	GetPlace(ctx context.Context, request GetPlaceRequestObject) (GetPlaceResponseObject, error)
	// Update or create an accessibility profile
	// (PATCH /places/{id}/accessibility)
	PatchPlaceAccessibility(ctx context.Context, request PatchPlaceAccessibilityRequestObject) (PatchPlaceAccessibilityResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RevokeKey operation middleware
func (sh *strictHandler) RevokeKey(w http.ResponseWriter, r *http.Request) {
	var request RevokeKeyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeKey(ctx, request.(RevokeKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeKeyResponseObject); ok {
		if err := validResponse.VisitRevokeKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPlaces operation middleware
func (sh *strictHandler) ListPlaces(w http.ResponseWriter, r *http.Request, params ListPlacesParams) {
	var request ListPlacesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlaces(ctx, request.(ListPlacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlacesResponseObject); ok {
		if err := validResponse.VisitListPlacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlace operation middleware
func (sh *strictHandler) CreatePlace(w http.ResponseWriter, r *http.Request) {
	var request CreatePlaceRequestObject

	var body CreatePlaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlace(ctx, request.(CreatePlaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlaceResponseObject); ok {
		if err := validResponse.VisitCreatePlaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlace operation middleware
func (sh *strictHandler) GetPlace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPlaceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlace(ctx, request.(GetPlaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlaceResponseObject); ok {
		if err := validResponse.VisitGetPlaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchPlaceAccessibility operation middleware
func (sh *strictHandler) PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchPlaceAccessibilityRequestObject

	request.Id = id

	var body PatchPlaceAccessibilityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchPlaceAccessibility(ctx, request.(PatchPlaceAccessibilityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchPlaceAccessibility")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchPlaceAccessibilityResponseObject); ok {
		if err := validResponse.VisitPatchPlaceAccessibilityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fpvb9s40v8qBJ/nRVvIf9J2F7d+l227i2B3USPZ3h3QBAotjiVuKFIlKcfawsB9iPuE90kOQ0q2ZMux",
	"N62zd8C9imKTQ87Mb2Z+M/Jnmui80AqUs3Tymdokg5z5x/MkAWvFTEjhqp9hARI/BVXmdPKRplpzGlEp",
	"cuEAn5SmNxF1VQF0Qq0zQqV0FXWlTI2eCwkopzC6AOME+LNAwoI5bfD5/w3M6YT+32hzs1F9rdG7et3U",
	"6MKieFDOMJXAwY31uvVGwXHLXJucOTqhZSlQCQOMv1eyohNnSuhRp2DmDh8PHDcNy9anFcxl96yyh/f5",
	"dZt9kiUQP/KuBqwzWueHDr2s161Ptbo0CcQGCm0CLISD/ODlr/y2S78LxdQXYsawyostZ7lwDniMarQU",
	"4szBwIkcjtGqLHD5F8qwYOIFGDEX4G27Z8dMawlM0dVGGz37DRJHI7ocpHpQf5hrDtIOe7HeWjkQubfN",
	"5DNVLN9spAEgdEJT4bJyNkx0PrpQf8sA5HuTjoS6x8cBK8SouEtH9S681RvmINWmaodmzqSkEWXC+NMi",
	"6gwTKraOOaEVDcBgpWEKv0zYHC9pM13gUi0kOLoBeivEIqpdBqY3zN/qJih3YjusfRg6uP1XXLeK6L3g",
	"aIuHN/QkpyOdtLnpaT2zVqnlGVY6nTMnEhrRnKmSSe+NhZaLYGulFfTat5v4dmzMSi5cPJcs7YZrT07o",
	"Bfo6RjkUjzN+RLnWJn608yKaMRujHrp18XUAhq9nhgkZ6sfughPjpuuB02KnW61O6G19uORu4qV2wlws",
	"gceG5cV+RwnlwCSh9PSvMJDrBZtJeECSsLFseMfut1bqAuICTALKPQ5yp4ZMx40nhowx2lyCLbSyfQQL",
	"v+7BiAfJp1IYrIMf62U329qh/KUDo5i8RENtS0+0mgsONQ/b1GRdznwFzNlS5JgCzyKaCxWex+tTVJnP",
	"wGxY2Q6Oc+aS7OGa/7BenjC1bnlznP9aOp/Wez8IkPxd46Oucef43b7wtlod9mqQsF7f5973V79sFyul",
	"ORr2nlV+qwzsoa84ddju6bJVossQ6Bs4jcfjcS+kMAGlAVNcWIdRGDsdH9su7K9QHLhIPAG1IlUshf0p",
	"jguLCY7HtmBJmws9YdXquOa0GO70LqdDAVrWOijs3ppxB2ZmnVYQzw3s8Y8tzZwdxsFVWPZE1LRjwRM7",
	"S9bab3mpffc/pGjT7mCctnqSh/avexfcY+CLuzqo03UseFCGc4E5i8lpR8kH5wStlL/qyZOPbMXltl47",
	"lfG7dh4bfNdXHGWYOzxUXv/SkeL/3RETIOSz6M+gUsTPy2++9fua/896VNA23x5ECOW+fU0P5V/ceEwP",
	"2JSgMGUB5fbMPXYzBlN3rcJ1Fr2MXt303STMNbZ0//Z1j0jslcvD0xoMoquw9KvNN1ydIfehd3fDNka/",
	"fEKyxR88YgKIAwpbMX4ckwrp5glS2rSuyN20xpljR4+xwl175lcKli5OSmMDS+NgEyMKz4om9H3BPpVA",
	"wtdkrg1xGRDcQgqWwpCczywoR+4zUMRlwhJh/RLJbLPkEgYWFCdMSjIX0oEhBTMst6RUScZUCpxoRYAl",
	"GbHlzMKnEkWiq8C64bU6yIO9Ifr4XxvK7YFF4sQCHZdIbf2YF6PZ927Ae7ngJaTCOjCX4VI9nUjOhOwA",
	"M3xy6OphVd/dN0fu635YIeI7qHa9dsnuyfn0gtxBRWym7xWBJUucrIhWCQzJldMGiHDEQlIakNWwLwEd",
	"Ubx2i1Vjhoe1bm4era3UOqzfGO1h7mlHB1867fGYFiqNHfLk/UQacjApqKSKi1LK/etSw2axYULaB+YO",
	"WspYqBi9DWYvh2yI0L5rhTlpbIG5OAORZo+cQLjSKLSAYVwcLjiPp5ZdWJw2EXfeA+wg0ECiDf+D0bKp",
	"3LBkeSG9ujbvW7pgstxaWYE9mF7qE5r9UeeefYHWbg3aGdMWGZNhgr5Az/pOxPrxw2wmwf9LI5oahu7z",
	"U4nEgPOtdninljBT+Bm8ExJsb5b9K5OC+4Z8z9BgPe/ZWGGx3kPmTEjo5VJ+VHD8K5/W3GKnYPaOltYn",
	"7JoU3YxZVrjqCsUHRc4L8RNU52XIMwKTdgaMA4qqAfv3wfn0YvCTz5LNFfwuukKhQs31buafljMpEnL5",
	"7upXXwGail1DnHQ6IVJI5hCpw2t1LiXBMkpA8UIL5SxhBsgCjBVaASel4mDIaHE2Gl6rqdEzaC19NsqA",
	"SZf9HpERptjq9+d+e6nWAuo6Lpz3WnOf8+kFgjMsohN6NhwPx55eF6BYIeiEvhqOh6/quPW2G7HSZaM7",
	"CO8dOUiE2W4NhIW+g0BGsA6WFjhxmuBmUM5POwJjaYgG9acaj6ULvhYRPGDqKuzPfDl+vXvgT1AR43dw",
	"VOD1+KyeIbp6kMuKQuKxQqvRb/WEKyDuYPvWmYJ693fP/kVYK1RKtCFC+Yho6n8HgHTysQu9jzerG2T4",
	"ec6wsa019jZr26krLdjf1PTEB6kOlKh7qTe+pFvC1JqMNHBMxQIU8bWfMM4NWDu8Vr9mQAy79yu9X7CM",
	"AO+QF/Kvf/yT2Ia/iDwHLphDCnOtLjHX1q/u0dWvSLhkcKklBRhyMfV/Ml2agMhtl9dahSgH677XvPpq",
	"jtymkatuOkFOstrB2tkJjt8PpcZVNSELUB5/tStsp/ieG1zUCA7U0J//3dOF0rnvDbwJmPS5jMBSWGdr",
	"8ArbutjLJ7wYopt4dBNYJgAcnbPqRm9wL2GKEwMJoCKb6AvB63974ZGVgutLmxh0ljDfvBE9J2EDQdZg",
	"gJNZRZ5tWnHy9t3Vm4hgvrl683x4ra7Kwv+8grjMABDkT5Y8y0tXMinRlIksrVjA88m1ImRAXryYGr1E",
	"raoXLybkVqr0NiK3kjn8E/jjrQ96bB+D0CZgiNMpuAxMI+p7XSqOeXCml15aLlRcS/SPQWrOlutP8ZG5",
	"zQlzXZr9B7yFOSulQ9m5ts4bWWFqqi1SG+ta3X66Jc8SZmEglAVlhQcVdreekxD/6ge73lus9rfPiUeE",
	"BUvuhcsIUxWaHlNl245spheAia7uqAUPGXq7r8ZuegGmarfTvhfvyXg/C+umARN+QsVycGCsLxWel3wq",
	"wVQbWuIRSKMWqnkwCp28HEedlxitEdrZ7uBqFfUfUI8i2ifscNz+nZ86m/7QIHCfyDAW2gj9sinl3lOY",
	"O/aUgwPVfWfUrVj7mHUw/tIIDE3xA8d/s/fV1KHz61B8AmvWkX5yi9Zp5Ck0Clnq62l0s0Myvl6F3wws",
	"e4rYlKVC+UwphXWb8vIn0gxva9LKfN2iivmxqYE+N4f8NJgxbCiKoA9KXEWHeDBRcB9EDUln5hE6r5xV",
	"ZAZEqESWHDgRSgoFu21JkNfMnk9BU+tZ8dOS09ahW5jBL/5EPrpZQqCZCfxXdncBOEjtalOv6eDos+Cr",
	"Yzihd4UPA+EsgfkcAl3emiuEt6bDa/WDNp3gQVppQLmIbAzhJwVCZWB84zY3OvfMJ6y8Vsi7kRCtdxBM",
	"Z35JkgnJCddgidKOcJgLhY2hBTkfXquLtdDWaQkzpiK3wsbrMycEwX3refNt/TNhwW8bChYu0keefgTX",
	"xGEfdfKjxnUWr9+ptuOpN6H3vxA8fc7eH3tz5NV/Yor+8OHiLant42/x+umCL1gA0VVboVMdfgRHGMHo",
	"lLAnrEY7vz4okPzvhtmHwkLonPbE09b4JFSSa3VecuGIf/nhQwm1LBH0FswCzMAKDiGq1q9yST1WrYif",
	"C9s+bE/xll77Tq16Mqh//bLW/8uOY6rc+AnusD2G6ANA3Wb+rwh2i+B/Qko4tgh/8C5ENZK6HKv+aA8n",
	"hxgOgVYaSSd0tDijq5vVvwMAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
