//go:build go1.22

// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	models "github.com/InWheelOrg/inwheel-server/pkg/models"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for A11yComponentType.
const (
	A11yComponentTypeElevator A11yComponentType = "elevator"
	A11yComponentTypeEntrance A11yComponentType = "entrance"
	A11yComponentTypeOther    A11yComponentType = "other"
	A11yComponentTypeParking  A11yComponentType = "parking"
	A11yComponentTypeRestroom A11yComponentType = "restroom"
)

// Valid indicates whether the value is a known member of the A11yComponentType enum.
func (e A11yComponentType) Valid() bool {
	switch e {
	case A11yComponentTypeElevator:
		return true
	case A11yComponentTypeEntrance:
		return true
	case A11yComponentTypeOther:
		return true
	case A11yComponentTypeParking:
		return true
	case A11yComponentTypeRestroom:
		return true
	default:
		return false
	}
}

// Defines values for A11yStatus.
const (
	Accessible   A11yStatus = "accessible"
	Inaccessible A11yStatus = "inaccessible"
	Limited      A11yStatus = "limited"
	Unknown      A11yStatus = "unknown"
)

// Valid indicates whether the value is a known member of the A11yStatus enum.
func (e A11yStatus) Valid() bool {
	switch e {
	case Accessible:
		return true
	case Inaccessible:
		return true
	case Limited:
		return true
	case Unknown:
		return true
	default:
		return false
	}
}

// Defines values for Category.
const (
	CategoryAirport      Category = "airport"
	CategoryCafe         Category = "cafe"
	CategoryEntrance     Category = "entrance"
	CategoryMall         Category = "mall"
	CategoryOther        Category = "other"
	CategoryParking      Category = "parking"
	CategoryRestaurant   Category = "restaurant"
	CategoryShop         Category = "shop"
	CategoryToilet       Category = "toilet"
	CategoryTrainStation Category = "train_station"
)

// Valid indicates whether the value is a known member of the Category enum.
func (e Category) Valid() bool {
	switch e {
	case CategoryAirport:
		return true
	case CategoryCafe:
		return true
	case CategoryEntrance:
		return true
	case CategoryMall:
		return true
	case CategoryOther:
		return true
	case CategoryParking:
		return true
	case CategoryRestaurant:
		return true
	case CategoryShop:
		return true
	case CategoryToilet:
		return true
	case CategoryTrainStation:
		return true
	default:
		return false
	}
}

// Defines values for OSMType.
const (
	Node     OSMType = "node"
	Relation OSMType = "relation"
	Way      OSMType = "way"
)

// Valid indicates whether the value is a known member of the OSMType enum.
func (e OSMType) Valid() bool {
	switch e {
	case Node:
		return true
	case Relation:
		return true
	case Way:
		return true
	default:
		return false
	}
}

// A11yComponent defines model for A11yComponent.
type A11yComponent = models.A11yComponent

// A11yComponentType defines model for A11yComponentType.
type A11yComponentType string

// A11yStatus defines model for A11yStatus.
type A11yStatus string

// AccessibilityProfile defines model for AccessibilityProfile.
type AccessibilityProfile = models.AccessibilityProfile

// Category defines model for Category.
type Category string

// ConflictError defines model for ConflictError.
type ConflictError struct {
	Conflicts []ConflictItem `json:"conflicts"`
	Error     string         `json:"error"`
}

// ConflictItem defines model for ConflictItem.
type ConflictItem struct {
	Component string `json:"component"`
	Reason    string `json:"reason"`
}

// ElevatorProperties defines model for ElevatorProperties.
type ElevatorProperties = models.ElevatorProperties

// EntranceProperties defines model for EntranceProperties.
type EntranceProperties = models.EntranceProperties

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// OSMType defines model for OSMType.
type OSMType string

// ParkingProperties defines model for ParkingProperties.
type ParkingProperties = models.ParkingProperties

// Place defines model for Place.
type Place = models.Place

// PlacePage defines model for PlacePage.
type PlacePage struct {
	Data []Place `json:"data"`

	// NextCursor Opaque cursor for the next page. Absent when this is the last page. Re-send all filter params unchanged on each subsequent request.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// ApiKey Raw API key shown exactly once. Store it securely.
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
}

// RestroomProperties defines model for RestroomProperties.
type RestroomProperties = models.RestroomProperties

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Error  string       `json:"error"`
	Fields []FieldError `json:"fields"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// ListPlacesParams defines parameters for ListPlaces.
type ListPlacesParams struct {
	Limit  *int     `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Lng    *float64 `form:"lng,omitempty" json:"lng,omitempty"`
	Lat    *float64 `form:"lat,omitempty" json:"lat,omitempty"`
	Radius *float64 `form:"radius,omitempty" json:"radius,omitempty"`
	MinLng *float64 `form:"min_lng,omitempty" json:"min_lng,omitempty"`
	MinLat *float64 `form:"min_lat,omitempty" json:"min_lat,omitempty"`
	MaxLng *float64 `form:"max_lng,omitempty" json:"max_lng,omitempty"`
	MaxLat *float64 `form:"max_lat,omitempty" json:"max_lat,omitempty"`
}

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreatePlaceJSONRequestBody defines body for CreatePlace for application/json ContentType.
type CreatePlaceJSONRequestBody = Place

// PatchPlaceAccessibilityJSONRequestBody defines body for PatchPlaceAccessibility for application/json ContentType.
type PatchPlaceAccessibilityJSONRequestBody = AccessibilityProfile

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Revoke the authenticated API key
	// (DELETE /auth/keys)
	RevokeKey(w http.ResponseWriter, r *http.Request)
	// Register and receive an API key
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// List places with cursor-based pagination
	// (GET /places)
	ListPlaces(w http.ResponseWriter, r *http.Request, params ListPlacesParams)
	// Create a place
	// (POST /places)
	CreatePlace(w http.ResponseWriter, r *http.Request)
	// Get a single place
	// (GET /places/{id})
	GetPlace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update or create an accessibility profile
	// (PATCH /places/{id}/accessibility)
	PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "radius"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lng", r.URL.Query(), &params.MinLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lat", r.URL.Query(), &params.MinLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lng", r.URL.Query(), &params.MaxLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lat", r.URL.Query(), &params.MaxLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_lat", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlace operation middleware
func (siw *ServerInterfaceWrapper) CreatePlace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlace operation middleware
func (siw *ServerInterfaceWrapper) GetPlace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchPlaceAccessibility operation middleware
func (siw *ServerInterfaceWrapper) PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchPlaceAccessibility(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/auth/keys", wrapper.RevokeKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/places", wrapper.ListPlaces)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/places", wrapper.CreatePlace)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/places/{id}", wrapper.GetPlace)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/places/{id}/accessibility", wrapper.PatchPlaceAccessibility)

	return m
}

type RevokeKeyRequestObject struct {
}

type RevokeKeyResponseObject interface {
	VisitRevokeKeyResponse(w http.ResponseWriter) error
}

type RevokeKey204Response struct {
}

func (response RevokeKey204Response) VisitRevokeKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeKey401JSONResponse ErrorResponse

func (response RevokeKey401JSONResponse) VisitRevokeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse RegisterResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse ValidationError

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register429JSONResponse ErrorResponse

func (response Register429JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlacesRequestObject struct {
	Params ListPlacesParams
}

type ListPlacesResponseObject interface {
	VisitListPlacesResponse(w http.ResponseWriter) error
}

type ListPlaces200JSONResponse PlacePage

func (response ListPlaces200JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces400JSONResponse ValidationError

func (response ListPlaces400JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaceRequestObject struct {
	Body *CreatePlaceJSONRequestBody
}

type CreatePlaceResponseObject interface {
	VisitCreatePlaceResponse(w http.ResponseWriter) error
}

type CreatePlace201JSONResponse Place

func (response CreatePlace201JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace400JSONResponse ValidationError

func (response CreatePlace400JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace401JSONResponse ErrorResponse

func (response CreatePlace401JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace422JSONResponse ConflictError

func (response CreatePlace422JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaceRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPlaceResponseObject interface {
	VisitGetPlaceResponse(w http.ResponseWriter) error
}

type GetPlace200JSONResponse Place

func (response GetPlace200JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlace400JSONResponse ValidationError

func (response GetPlace400JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlace404JSONResponse ErrorResponse

func (response GetPlace404JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibilityRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchPlaceAccessibilityJSONRequestBody
}

type PatchPlaceAccessibilityResponseObject interface {
	VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error
}

type PatchPlaceAccessibility200JSONResponse AccessibilityProfile

func (response PatchPlaceAccessibility200JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility400JSONResponse ValidationError

func (response PatchPlaceAccessibility400JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility401JSONResponse ErrorResponse

func (response PatchPlaceAccessibility401JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility404JSONResponse ErrorResponse

func (response PatchPlaceAccessibility404JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility422JSONResponse ConflictError

func (response PatchPlaceAccessibility422JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Revoke the authenticated API key
	// (DELETE /auth/keys)
	RevokeKey(ctx context.Context, request RevokeKeyRequestObject) (RevokeKeyResponseObject, error)
	// Register and receive an API key
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// List places with cursor-based pagination
	// (GET /places)
	ListPlaces(ctx context.Context, request ListPlacesRequestObject) (ListPlacesResponseObject, error)
	// Create a place
	// (POST /places)
	CreatePlace(ctx context.Context, request CreatePlaceRequestObject) (CreatePlaceResponseObject, error)
	// Get a single place
	// (GET /places/{id})
	GetPlace(ctx context.Context, request GetPlaceRequestObject) (GetPlaceResponseObject, error)
	// Update or create an accessibility profile
	// (PATCH /places/{id}/accessibility)
	PatchPlaceAccessibility(ctx context.Context, request PatchPlaceAccessibilityRequestObject) (PatchPlaceAccessibilityResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RevokeKey operation middleware
func (sh *strictHandler) RevokeKey(w http.ResponseWriter, r *http.Request) {
	var request RevokeKeyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeKey(ctx, request.(RevokeKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeKeyResponseObject); ok {
		if err := validResponse.VisitRevokeKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPlaces operation middleware
func (sh *strictHandler) ListPlaces(w http.ResponseWriter, r *http.Request, params ListPlacesParams) {
	var request ListPlacesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlaces(ctx, request.(ListPlacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlacesResponseObject); ok {
		if err := validResponse.VisitListPlacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlace operation middleware
func (sh *strictHandler) CreatePlace(w http.ResponseWriter, r *http.Request) {
	var request CreatePlaceRequestObject

	var body CreatePlaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlace(ctx, request.(CreatePlaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlaceResponseObject); ok {
		if err := validResponse.VisitCreatePlaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlace operation middleware
func (sh *strictHandler) GetPlace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPlaceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlace(ctx, request.(GetPlaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlaceResponseObject); ok {
		if err := validResponse.VisitGetPlaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchPlaceAccessibility operation middleware
func (sh *strictHandler) PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchPlaceAccessibilityRequestObject

	request.Id = id

	var body PatchPlaceAccessibilityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchPlaceAccessibility(ctx, request.(PatchPlaceAccessibilityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchPlaceAccessibility")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchPlaceAccessibilityResponseObject); ok {
		if err := validResponse.VisitPatchPlaceAccessibilityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FrhbuO4EX6VgVqgdwvHdrK5Q8//ctm9Q7C3WCPZbQusA4eWxhYvFKklKSe6hYE+RJ+wT1IMKdmSRcfu",
	"bZK9Av2V2CKHw+E333xD+XMUqyxXEqU10ehzZOIUM+b+PTs+Ls/rh/RFrlWO2nJ0j1mRcDudC7ZwH7nF",
	"zP1jyxyjUWSs5nIRrXr1F0xrVtJnFLhkVmka/GeN82gU/Wmw8WJQuTB4XY0bb5al2dJqJmPcO7sa157N",
	"zZTLFDW3mDScnSklkEkakaFlCbPMbTFJuOVKMtGwMrK6wPWu1OxXjC1NVEvUTIipscwWZp97FNwrP3LV",
	"i3KmbylaeyaN/bD2ljQaq5XK9k2+rMa1ZxtV6Bin3EVjrnTGbDSKioInUW/XUe7f2Ro272nCynn5qeCa",
	"gv7RW7neDmEvuj9aqKPqy0wlKEy/jcHGkCOe5Uo7WEqWbWZEFEybRqNowW1azPqxygYX8u8poninFwMu",
	"7+jfI4N6iXqQ3y4G1UTysuv76HOEssjI7TXyGjHfHF0D171I2RR1Y4ubCDbOvWGaxTEaw2eCjAueOXj2",
	"Ii5bDwp5K9WdDNutBnLBbTnWas4FdnO2nevrlD34OEPpHIaORpa8k6LcSpeNw1+ULoLtxOzehYs8YRaT",
	"KbOt6fTlkeUZ7rexBeetnRwI7NB5PTm+z5nFhdJlE3sZEyLqRYxrt2Avsppx6XbDlazAzgrNXALGbE5+",
	"mlTlNFRxgbadBZss2Z0F50rOBY/ta619HdiGqX98OEprgxcWs2DNqRfCe5blwj1rngAQ5UOspGVcGtg4",
	"sO/wveFew+XrQG1oubc7K4PlUyMzSgYebXkSN2iymhNyJVBVg6VdhcvjTDMuPLV0HyaYEzSbWaUKz10Z",
	"u+cZAe542IsyLv2H4dpBWWQz1GTkjidfamR1UAoGIvHkCRhQJZ3op8xMNcvycIzpqbG44yk3U1ZYlTHL",
	"4/AImjtNkS9Suy/If5iD6gbt6Q+K8voSTa6kCRTSNZ8cwg6hNPyJo0h20N+cnn0RF3gLD/LAu6u32wJH",
	"qoQO746VbqrwBSDE310hGiC1whNaAwvDYRgOXFpceFARvBNu2ExgMjU5i9GEcHwYcLpuPjluxiRNAoza",
	"LDZ7xU5IG6yo9m6q94PFsB5HczR+odr53QpPsH0M80MTDkc/hEhG+K7oIYr5a8uK+9gx40/YgfEXlAs6",
	"3pPvvnfz6s/HIZFqsm2ZyaX9/jTaB2OaeEizVGeh7wFR2kM7Mc3kbSN3j3snvZfXIU98g7e19+9PQ81d",
	"1cmHu97djf2GUx5dWrtj80jyUGgkwWE62+fj86T9mC0CqV9fJhykY727AQEr8d5O40IbXzASNLHmuSPo",
	"UfQuZ58KBP8Y5kqDTRFoCuRsgX04mxmUFu5SlGBTboAbN0QwUw+5xCODMgEmBMy5sKghZ5plBgoZp0wu",
	"MAElAVmcgilmBj8VZJJOC43tT+ReqewCESpFl7jgxqK+9LYC1TZjXLQg5b/ZK87dqIeX3FXhWc6nt1h2",
	"g33J7uBsfAG3WIJJ1Z0EvGexFSUoGWMfrqzSCNyCwbjQKMp+KH8P4OXOnHUYHt517XlvHaXGYuFgdG6G",
	"uuWcIMDlYmqpNO+Q/0rp6SOowl600Gw2pU7DhFdyqRinjOtp44bkd+uEQACenDH+xgRPnMLaoQIDLety",
	"PQfmjAsMVgan/Q7vnBtCtEM7O3rdaoUulKjcEOi5La/IvN/IWc7fYHlWeFhwyqEUWYJkqgroP47OxhdH",
	"bxxoaxfcrGhFRrmcq24ijouZ4DFcvr567xKy5r3qCKDd4OeCWYJkfyLPhPD9PsokV1xaA0wjLFEbriQm",
	"UMgENQyWx4P+RI61mmFj6DeDFJmw6W89GFA1K3/71k0v5NpAxYbculOr/TkbX0S9qBoUjaLj/rA/dGIh",
	"R8lyHo2il/1h/2WFKxe7AStsOrjF0pcSFGgxQEm4VLfoKZ1oqTCYgFVAk1FaTjXT835N15FbVTssXSRr",
	"E/4EdEWKbs2T4Wl3wTdYgnYzEtrA6fC4urax1S0Gy3NBy3IlB79WLYtH3N57+1bj5Y6/vfZbbgyXC1Aa",
	"uHQZUdNxC4DR6GMbeh+vV9e9yBRZxkhCVzt2MWvGqW3Nx19X1cIlqfIVqu3UuWNYA0yua0MNxwVfogRH",
	"xcCSRKMx/Yl8nyJodudGunOxhSboNWsJ/Puf/wJTlxOeZZhwZqmiTOQlFYrqppiO+iV4J/2RGshRw8XY",
	"/UlVoT0it4+82pXPcjT2R5WUj3aQ21V91aYTkn+rDtaOn2D53VCqj6qqjx7Kw0dzYZviAx5cVAj2ldqt",
	"/8PzpdJZbPnSUwYTjssA77mxpgIvNw3HTp7RMUI3OHQD3seICR3Oqp29/niByQQ0xkgb2WSfT173nsAh",
	"a4E2RJuUdAaYk8Cg5uAngNIJakxgVsI3m54GXr2+Ou8B8c3V+bf9ibwqchIGxLsaEai4G/gmK2zBhKBQ",
	"xqIwfInfjiYS4AhevBhrdU+7Kl+8GMGNkIubHtwIZumPZgkvzI1LehLh3midMGDVAm2Kujb1oypkQjw4",
	"U/fOWsbltLLo/vVWM3a//pb+ZXazwlwVevcCr3DOCmHJdqaMdUGWRE1VRKpgTWTdOfDEc+h2/0BdwxJ1",
	"2WwbXM8R4KRfuLFjf2quI2YZWtTGkblTDp8K1OVGODiMRL0G7hLvdjQ6GbYUZ1NyHncb5VUvvEDVcjVX",
	"6KjvHa65dnUz7cuuMHauwuyhq+y9bdm1hkdma5k1tt/WBn07/8Dy3+28/tu3foXsZ4hmlThPHtEqK59j",
	"Rz7pH29H152a/XgFc3OLEqgJY7bg0hGP4MZu2PorVm0Xa2jQVLtGEZnVJeWO27S6oDmaMdLnud8PWVz1",
	"9slKkHjnTfXhrPviMmMlzBC4jEWRYAJcCi6xq/K9vfpO7ClUX3WB9bxar7HoFmbowVeUd5shgHWL/Ydp",
	"lkjTnTyaK+1X+kGxecj79v+qhfNwJv1WAWCt+QafebI6RPg5gLjk5NYAzufoNfHW5YF/CdOfyJ+UbqU0",
	"aUeN0vZgExN3HbD+mRnMtcpcJ+hHTiSJaybLzQwgknVD4pSLBBKFBqSykOCcS+r+DIp5fyIv1kYbq8VM",
	"6xJumj9tGwGl3I0Txzfrn3jdEGluHAnpr5/R1uwQUl/uvmtdW6rXQM0sD5aZ8DuMp68kuxlhTuL5KxaO",
	"Dx8uXkEVH+fF6fNRgo8AoauKQqtm/YwWGBBnCNyRVoPOy8yc2TjtptmH3KBvj3bk09Ydia9vE3lWJNyC",
	"+2WpSyXaZbHOJFPMMm5bOQCbm9M+9SM+u09PToDP25n2FwP+Z1qQcI3upoWiTgo3tsZxANusHsqQMe3V",
	"xbBFaM+WMI9fssOvmw+p4MNn8OGhIlLDqOpI/1/gOwX+qxLL/77A+OCARcGNK6khw0zm/fFvenz6F1pE",
	"o2iwPI5W16v/BAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
