//go:build go1.22

// Package apiv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package apiv1

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	models "github.com/InWheelOrg/inwheel-api/pkg/models"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes apiKeyAuthContextKey = "ApiKeyAuth.Scopes"
)

// Defines values for AccessibilityLevel.
const (
	Good    AccessibilityLevel = "good"
	Limited AccessibilityLevel = "limited"
	No      AccessibilityLevel = "no"
)

// Valid indicates whether the value is a known member of the AccessibilityLevel enum.
func (e AccessibilityLevel) Valid() bool {
	switch e {
	case Good:
		return true
	case Limited:
		return true
	case No:
		return true
	default:
		return false
	}
}

// Defines values for Category.
const (
	Airport      Category = "airport"
	Cafe         Category = "cafe"
	Entrance     Category = "entrance"
	Mall         Category = "mall"
	Other        Category = "other"
	Parking      Category = "parking"
	Restaurant   Category = "restaurant"
	Shop         Category = "shop"
	Toilet       Category = "toilet"
	TrainStation Category = "train_station"
)

// Valid indicates whether the value is a known member of the Category enum.
func (e Category) Valid() bool {
	switch e {
	case Airport:
		return true
	case Cafe:
		return true
	case Entrance:
		return true
	case Mall:
		return true
	case Other:
		return true
	case Parking:
		return true
	case Restaurant:
		return true
	case Shop:
		return true
	case Toilet:
		return true
	case TrainStation:
		return true
	default:
		return false
	}
}

// Defines values for DoorType.
const (
	Automatic DoorType = "automatic"
	Manual    DoorType = "manual"
	None      DoorType = "none"
	Revolving DoorType = "revolving"
)

// Valid indicates whether the value is a known member of the DoorType enum.
func (e DoorType) Valid() bool {
	switch e {
	case Automatic:
		return true
	case Manual:
		return true
	case None:
		return true
	case Revolving:
		return true
	default:
		return false
	}
}

// Defines values for OSMType.
const (
	Node     OSMType = "node"
	Relation OSMType = "relation"
	Way      OSMType = "way"
)

// Valid indicates whether the value is a known member of the OSMType enum.
func (e OSMType) Valid() bool {
	switch e {
	case Node:
		return true
	case Relation:
		return true
	case Way:
		return true
	default:
		return false
	}
}

// Defines values for PlaceStatus.
const (
	Active     PlaceStatus = "active"
	Closed     PlaceStatus = "closed"
	OsmRemoved PlaceStatus = "osm_removed"
)

// Valid indicates whether the value is a known member of the PlaceStatus enum.
func (e PlaceStatus) Valid() bool {
	switch e {
	case Active:
		return true
	case Closed:
		return true
	case OsmRemoved:
		return true
	default:
		return false
	}
}

// Defines values for SurfaceType.
const (
	Asphalt      SurfaceType = "asphalt"
	Carpet       SurfaceType = "carpet"
	Cobblestone  SurfaceType = "cobblestone"
	Concrete     SurfaceType = "concrete"
	Gravel       SurfaceType = "gravel"
	PavingStones SurfaceType = "paving_stones"
	Tiles        SurfaceType = "tiles"
	Wood         SurfaceType = "wood"
)

// Valid indicates whether the value is a known member of the SurfaceType enum.
func (e SurfaceType) Valid() bool {
	switch e {
	case Asphalt:
		return true
	case Carpet:
		return true
	case Cobblestone:
		return true
	case Concrete:
		return true
	case Gravel:
		return true
	case PavingStones:
		return true
	case Tiles:
		return true
	case Wood:
		return true
	default:
		return false
	}
}

// AccessibilityLevel Traffic-light rating for a measurement field, submitted directly rather
// than measured. `good` and `limited` bands, and the `no` cutoff, are
// defined per-field against SIA 500 or ADA and documented on that field.
type AccessibilityLevel string

// AccessibilityProfile defines model for AccessibilityProfile.
type AccessibilityProfile = models.AccessibilityProfile

// Category Broad place type used for filtering and icon selection.
// `entrance` and `toilet` denote standalone accessibility-relevant
// features rather than full venues; `other` is the ingestion fallback
// for buildings that don't fit a more specific category.
type Category string

// DoorProps defines model for DoorProps.
type DoorProps = models.DoorProps

// DoorType defines model for DoorType.
type DoorType string

// ElevatorProps defines model for ElevatorProps.
type ElevatorProps = models.ElevatorProps

// EntranceProps defines model for EntranceProps.
type EntranceProps = models.EntranceProps

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error string `json:"error"`
}

// ExternalRef defines model for ExternalRef.
type ExternalRef = models.ExternalRef

// FieldError defines model for FieldError.
type FieldError struct {
	Field  string `json:"field"`
	Reason string `json:"reason"`
}

// OSMType OpenStreetMap element type this place was ingested from.
type OSMType string

// ParkingProps defines model for ParkingProps.
type ParkingProps = models.ParkingProps

// PathwayProps defines model for PathwayProps.
type PathwayProps = models.PathwayProps

// Place defines model for Place.
type Place = models.Place

// PlacePage defines model for PlacePage.
type PlacePage struct {
	Data []Place `json:"data"`

	// NextCursor Opaque cursor for the next page. Absent when this is the last page. Re-send all filter params unchanged on each subsequent request.
	NextCursor *string `json:"next_cursor,omitempty"`
}

// PlaceStatus Lifecycle state of an OSM-sourced place. `osm_removed` means the
// backing OSM element was deleted upstream but the place record is
// kept to preserve any user-submitted accessibility data.
type PlaceStatus string

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email openapi_types.Email `json:"email"`
}

// RegisterResponse defines model for RegisterResponse.
type RegisterResponse struct {
	// ApiKey Raw API key shown exactly once. Store it securely.
	ApiKey    string    `json:"api_key"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
}

// RestroomProps defines model for RestroomProps.
type RestroomProps = models.RestroomProps

// SourceReport defines model for SourceReport.
type SourceReport struct {
	RecordedAt time.Time `json:"recorded_at"`
	Source     string    `json:"source"`
	Value      string    `json:"value"`
}

// SurfaceType defines model for SurfaceType.
type SurfaceType string

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Error  string       `json:"error"`
	Fields []FieldError `json:"fields"`
}

// apiKeyAuthContextKey is the context key for ApiKeyAuth security scheme
type apiKeyAuthContextKey string

// ListPlacesParams defines parameters for ListPlaces.
type ListPlacesParams struct {
	Limit  *int     `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *string  `form:"cursor,omitempty" json:"cursor,omitempty"`
	Q      *string  `form:"q,omitempty" json:"q,omitempty"`
	Lng    *float64 `form:"lng,omitempty" json:"lng,omitempty"`
	Lat    *float64 `form:"lat,omitempty" json:"lat,omitempty"`
	Radius *float64 `form:"radius,omitempty" json:"radius,omitempty"`
	MinLng *float64 `form:"min_lng,omitempty" json:"min_lng,omitempty"`
	MinLat *float64 `form:"min_lat,omitempty" json:"min_lat,omitempty"`
	MaxLng *float64 `form:"max_lng,omitempty" json:"max_lng,omitempty"`
	MaxLat *float64 `form:"max_lat,omitempty" json:"max_lat,omitempty"`
}

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreatePlaceJSONRequestBody defines body for CreatePlace for application/json ContentType.
type CreatePlaceJSONRequestBody = Place

// PatchPlaceAccessibilityJSONRequestBody defines body for PatchPlaceAccessibility for application/json ContentType.
type PatchPlaceAccessibilityJSONRequestBody = AccessibilityProfile

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Revoke the authenticated API key
	// (DELETE /auth/keys)
	RevokeKey(w http.ResponseWriter, r *http.Request)
	// Register and receive an API key
	// (POST /auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// List places with cursor-based pagination
	// (GET /places)
	ListPlaces(w http.ResponseWriter, r *http.Request, params ListPlacesParams)
	// Create a place
	// (POST /places)
	CreatePlace(w http.ResponseWriter, r *http.Request)
	// Get a single place
	// (GET /places/{id})
	GetPlace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update or create an accessibility profile
	// (PATCH /places/{id}/accessibility)
	PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// RevokeKey operation middleware
func (siw *ServerInterfaceWrapper) RevokeKey(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeKey(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlaces operation middleware
func (siw *ServerInterfaceWrapper) ListPlaces(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lng", r.URL.Query(), &params.Lng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "lat", r.URL.Query(), &params.Lat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "radius" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "radius", r.URL.Query(), &params.Radius, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "radius"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "radius", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lng", r.URL.Query(), &params.MinLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "min_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "min_lat", r.URL.Query(), &params.MinLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "min_lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "min_lat", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_lng" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lng", r.URL.Query(), &params.MaxLng, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_lng"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_lng", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "max_lat" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "max_lat", r.URL.Query(), &params.MaxLat, runtime.BindQueryParameterOptions{Type: "number", Format: "double"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "max_lat"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "max_lat", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlaces(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreatePlace operation middleware
func (siw *ServerInterfaceWrapper) CreatePlace(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreatePlace(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetPlace operation middleware
func (siw *ServerInterfaceWrapper) GetPlace(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetPlace(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PatchPlaceAccessibility operation middleware
func (siw *ServerInterfaceWrapper) PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, ApiKeyAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PatchPlaceAccessibility(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/auth/keys", wrapper.RevokeKey)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/register", wrapper.Register)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/places", wrapper.ListPlaces)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/places", wrapper.CreatePlace)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/places/{id}", wrapper.GetPlace)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/places/{id}/accessibility", wrapper.PatchPlaceAccessibility)

	return m
}

type RevokeKeyRequestObject struct {
}

type RevokeKeyResponseObject interface {
	VisitRevokeKeyResponse(w http.ResponseWriter) error
}

type RevokeKey204Response struct {
}

func (response RevokeKey204Response) VisitRevokeKeyResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type RevokeKey401JSONResponse ErrorResponse

func (response RevokeKey401JSONResponse) VisitRevokeKeyResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RegisterRequestObject struct {
	Body *RegisterJSONRequestBody
}

type RegisterResponseObject interface {
	VisitRegisterResponse(w http.ResponseWriter) error
}

type Register201JSONResponse RegisterResponse

func (response Register201JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Register400JSONResponse ValidationError

func (response Register400JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type Register409JSONResponse ErrorResponse

func (response Register409JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type Register429JSONResponse ErrorResponse

func (response Register429JSONResponse) VisitRegisterResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlacesRequestObject struct {
	Params ListPlacesParams
}

type ListPlacesResponseObject interface {
	VisitListPlacesResponse(w http.ResponseWriter) error
}

type ListPlaces200JSONResponse PlacePage

func (response ListPlaces200JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListPlaces400JSONResponse ValidationError

func (response ListPlaces400JSONResponse) VisitListPlacesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlaceRequestObject struct {
	Body *CreatePlaceJSONRequestBody
}

type CreatePlaceResponseObject interface {
	VisitCreatePlaceResponse(w http.ResponseWriter) error
}

type CreatePlace201JSONResponse Place

func (response CreatePlace201JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace400JSONResponse ValidationError

func (response CreatePlace400JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreatePlace401JSONResponse ErrorResponse

func (response CreatePlace401JSONResponse) VisitCreatePlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlaceRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetPlaceResponseObject interface {
	VisitGetPlaceResponse(w http.ResponseWriter) error
}

type GetPlace200JSONResponse Place

func (response GetPlace200JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlace400JSONResponse ValidationError

func (response GetPlace400JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetPlace404JSONResponse ErrorResponse

func (response GetPlace404JSONResponse) VisitGetPlaceResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibilityRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *PatchPlaceAccessibilityJSONRequestBody
}

type PatchPlaceAccessibilityResponseObject interface {
	VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error
}

type PatchPlaceAccessibility200JSONResponse AccessibilityProfile

func (response PatchPlaceAccessibility200JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility400JSONResponse ValidationError

func (response PatchPlaceAccessibility400JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility401JSONResponse ErrorResponse

func (response PatchPlaceAccessibility401JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type PatchPlaceAccessibility404JSONResponse ErrorResponse

func (response PatchPlaceAccessibility404JSONResponse) VisitPatchPlaceAccessibilityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Revoke the authenticated API key
	// (DELETE /auth/keys)
	RevokeKey(ctx context.Context, request RevokeKeyRequestObject) (RevokeKeyResponseObject, error)
	// Register and receive an API key
	// (POST /auth/register)
	Register(ctx context.Context, request RegisterRequestObject) (RegisterResponseObject, error)
	// List places with cursor-based pagination
	// (GET /places)
	ListPlaces(ctx context.Context, request ListPlacesRequestObject) (ListPlacesResponseObject, error)
	// Create a place
	// (POST /places)
	CreatePlace(ctx context.Context, request CreatePlaceRequestObject) (CreatePlaceResponseObject, error)
	// Get a single place
	// (GET /places/{id})
	GetPlace(ctx context.Context, request GetPlaceRequestObject) (GetPlaceResponseObject, error)
	// Update or create an accessibility profile
	// (PATCH /places/{id}/accessibility)
	PatchPlaceAccessibility(ctx context.Context, request PatchPlaceAccessibilityRequestObject) (PatchPlaceAccessibilityResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// RevokeKey operation middleware
func (sh *strictHandler) RevokeKey(w http.ResponseWriter, r *http.Request) {
	var request RevokeKeyRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.RevokeKey(ctx, request.(RevokeKeyRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RevokeKey")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RevokeKeyResponseObject); ok {
		if err := validResponse.VisitRevokeKeyResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Register operation middleware
func (sh *strictHandler) Register(w http.ResponseWriter, r *http.Request) {
	var request RegisterRequestObject

	var body RegisterJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Register(ctx, request.(RegisterRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Register")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(RegisterResponseObject); ok {
		if err := validResponse.VisitRegisterResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListPlaces operation middleware
func (sh *strictHandler) ListPlaces(w http.ResponseWriter, r *http.Request, params ListPlacesParams) {
	var request ListPlacesRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListPlaces(ctx, request.(ListPlacesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListPlaces")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListPlacesResponseObject); ok {
		if err := validResponse.VisitListPlacesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreatePlace operation middleware
func (sh *strictHandler) CreatePlace(w http.ResponseWriter, r *http.Request) {
	var request CreatePlaceRequestObject

	var body CreatePlaceJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreatePlace(ctx, request.(CreatePlaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreatePlace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreatePlaceResponseObject); ok {
		if err := validResponse.VisitCreatePlaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetPlace operation middleware
func (sh *strictHandler) GetPlace(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetPlaceRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetPlace(ctx, request.(GetPlaceRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetPlace")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetPlaceResponseObject); ok {
		if err := validResponse.VisitGetPlaceResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// PatchPlaceAccessibility operation middleware
func (sh *strictHandler) PatchPlaceAccessibility(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request PatchPlaceAccessibilityRequestObject

	request.Id = id

	var body PatchPlaceAccessibilityJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.PatchPlaceAccessibility(ctx, request.(PatchPlaceAccessibilityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "PatchPlaceAccessibility")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(PatchPlaceAccessibilityResponseObject); ok {
		if err := validResponse.VisitPatchPlaceAccessibilityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fvvcts4kn+VLt5tXTJF0fLfON7KB89kdso1k4vLzuxdVZSSIKIpYg0CDADK1qRcdQ9xT3hPctUAKZES",
	"ZTs7Vub2aj9ZogB0o//+upv+EqW6KLVC5Wx09iWyaY4F8x/P0xStFVMhhVv8gnOU9JSjTY0ondAqOos+",
	"GJZlIh1IMcsdGOaEmkGmDTAokNnKYIHKQSZQ8hhsNS2Ec8iBC4OpkwvakqMZKZcz1WzhCUxmWvMJMMVh",
	"IkUhHPIJTJniNvYPXY4wUXoCaeV0lsXADI4Ux0wo5FCiGXiSwGZMKOvg+uIcjodD0AbO3577I7hOK2IO",
	"OWgFLmc1m8lIRXGEqiqis48R8RHFUc1DFEdKR5/iyC1KjM4i64xQs+g+7grr0uhMSCRxlUaXaJxAL1KU",
	"OGdOG/r8rwaz6Cz6l72VAvZq6e/9WK+7NLq0dDwqZ5hK8dGN9brlRsFpS6ZNwVx0FlWVoEsYZPy9kovo",
	"zJkKe65TMnNDHx8hdxmWLamVzOW3bGEf3+fXrfZJluL47+TVoHVG6+Ixolf1uiVVqyuT4thgqU2wfuGw",
	"eJT5a7/tyu+iY2qGmDFs4Y9trHxM12hdiDOHAycKfMqtqpKW/84zLJrxHI3IBHrZbtkx1VoiU9H96jZ6",
	"+jdMXRRHd4OZHtQPC81R2qTX1lsrB6Lwsjn7EilWrDZGwUCis2gmXF5Nk1QXexfqP3JE+d7M9oS6pY8D",
	"Voq98ma2V+8irn5gDmfaLDYj0PdGMw7egICIQ2WR+xCUCemQROHdXaRagUWJKW1MRmrS+FQdZpwWEt0E",
	"OCrtEKxjijOpFQJr33dgvBMrN1IZMlcZtHUQAx/DskpKmKOq0P4ZJpp+mICwPmIJNUNL5CFjUk5ZejNS",
	"xOm0EpILNbMhDHGt/o2CkaMoqg2CLTEVmUghrcXQjVEFkzKKIyaMF3scOcOEGlvHvIyCh7DKMEU/piwj",
	"bdlcl7TU3zpaeXwr1sSRZ7833r3VTXTaCHJh7cM+RNs/0Lr7OLoVnIziS8SkfJ9FZx8f3tqTlu4/xWtW",
	"8YNEZkCXqEj/nkICFMthVA2Hh/hmmJwOixjquA7D5NVwUD9TOixK6WEBL+rc8TJ5qn+sZLNbp1gKkTJL",
	"bQuscrpgTqRRHBVMVUx6/c+1nAftKq2wV6PdnLOhVVZx4caZZLNupOwJx70xZhkeOZbPr242FQr8yV01",
	"7yeHbTXvJ/vDQf1sqWZ6WMCL87fnpOI44lqb8S6Msmt/r7v2d0r293rN/k47jOXMjkkNuiX3ZegOP08N",
	"EzIgj80FO3E0L/keB9sn52lL/pgk/2pN8setCz7NubpmulsH66KpHbqEfhwSroJKrepM3CEfG1aU281B",
	"KIcmDdCof4XBQs/ZVOIDJwk7lg383/zVSl3iuESTonLPbF1XrCjBE2gbV/rm5E8ryzoZnCaHh39amRX6",
	"7y2/+X+XYLp2uWMfMEabK7SlVravoqGfe4zeW/3nShgCnh/rZZ/Wb0fn3zk0iskrUsj66alWmeBYFz4r",
	"EKyrqYecBbsTBSW+/TgqhAqfh0sqqiqmaFZl0IZjFsyl+cMg++F7+QqlxeWnp+mvdefdau8vVNH+2Oio",
	"K1xf7W6LV5as/DGthhOW6/vU+/76XQNRug70vkR17Qyie8dKQBkaBR7Bu1zYGtHfMlujZgL1RhdJC/cq",
	"zUlDt2zheZAB7vZhm06durs4nuoqhMCVXQ6Hw2GvbVJongXj5IKKjRTHTo/bhf5OoEf65uC4FZcOjgfH",
	"7ZiETUZuig609Ft9oT+DQkbVBLA5E5LyBmRiVplQdq1gCkcuUl+/WjFTbIbbMxAXls7hY1uytF1B7Bq6",
	"1EYBnm5fCD9Ijtoh/CAZDgf1s2UIp4dfC2E61rhb/+80WnZn+KRH67C0WwHEDZqpdVrhODO4xRpsZTL2",
	"eI/rOizbZfn478wYfUt2XjJr2Qz7M/zXQvinmkdLZzs2D1nLG+9YUYa6odPtCKVlKyS1LebjpzY2DJZR",
	"ayP0TYlEuuzcbLQlKClHhxk7Pc5OjgbHr/ZfDY6OTw4G08MsHRykr08Os5MTlrGTKI4kJeajk+To5PAg",
	"jqSaRWcnyenRwUHcCOMnZhA4wl9xjpQQtC18R3H/4PDo+OTV6evwqIEGIXcYpm48eiCuKks2nTox94a1",
	"5ivrYnmykTUdso4wHt6/bHfRHoO/uxGINeAYCx4uw7kgJTB52bnkg63lFmi578n0f2f3Vq7fawPbvW4n",
	"0MHrPngnQ6v6IYB42jnFf904JliST9+/oJqRIR8cn/h9zff9nis0ltZiQCh3chQ9lvhX9viw6BsQFRrz",
	"qNyWVvlm3PbmvQ693gpbSraA0ghthFv4bmnBSkilILoJ7MMbkEzxgpkbeGFzfauAObjVRvKR+k3rIgZM",
	"ZgnUPUcbQ65tKRyT9mUMB/AG0Do2lcLmHte9CO1Uw0cq1UWBJhVM7pXVVIp02f58GcMhvIG6rQovCqG0",
	"gcp5LwoER6reE/qWNobzD+8s/M9//TcELrWSC2I1F7MciNGXnV7pfnwQH37q00UYBqxp/+SoR6hNqHhk",
	"xEGh9TosfbahgKsz9Tb/3dyw7qW/f6ywVgN4nwluHPywFeWeVg2FJPQNEt1ljUO7gZ0zx548+wm89gx9",
	"FN65cVoZGyqt9VqHfa4Qws/e21yOQFugZDNM4HxqyUtuc1Sh+qkHBpLZZskVDiwqDkzKerIBJTOssFCp",
	"NGdqFuaYyNIcbDW1+LmiI0lVaF1wgoc16QXRV8O1TXnjbr+IDNNFKv3ExCHoDJiC99fvBsGj6tlMAhOK",
	"dr7dhHwCBTLl7zhSU5Z6HP7++t2yDqS6j6NEAlZVaZ1BVsC0cl4qoTQ0mGrDQdiRusHSgdNQGrRo5ghM",
	"LaggMYPVxLmTv4Hu2h2i1Hk/jlKprZ/0tvjtLSqvcCasQ3MVRNzTGymYkB03C08eU0RY1aeJFclt/RhW",
	"ivEN9szJrtgtnF9ewA0u6lCJd8yP4LUi9Vw7bRCEA4tpZVAukr6E8gQwsgk+GjE8fOuG83gppRaxfmG0",
	"57m77c6O/4F6iKEc8zFBqNmY0vAD5TcWaGao0sW4rKTcvm5m2HRsmJD2gWaylnJMED/Xt2i21oKNK25j",
	"K+T2sUXmxjmKWe520Q0ZJkeHg2FydNqR8BFJ+OiwAG3o2+lgmDT9EV05KziGGe2qu+wqQ/obG8ZFCJA7",
	"GhntB05WE5WD4WA/OV6bqBx8db3Z9aPd5uHOuxMbLhtC+leGlxVwWxaxFLr7ls6ZrNZWLtA+Go9rCs3+",
	"uMNnX2Rqdyjas1lb5kyGYfucTMY3RKzvIE+nEv3XKI5mhpE1+MZyatD5Jmd4DyllpvTjeick2t609Fcm",
	"Bfcl9pa+77Jlv5LCfLkHMiYk9hYTvtv79NdkWq3nDbzUOx1YUtgUKamZ0pJwi2s6PlzkvBQ/4+K8CoFZ",
	"kL/kyDjSUbXB/ufg/PJi8LNPKw0Lfld0T4cKlenNVHkZSoyrH68/+JTZALbaxNegRCmZI0tNRupcSo8s",
	"ABUvtVDOAjMIczRWaEVQRnE0sDff30tG6tLoKbaWvtjLkUmX/xbDHuWkxW8v/fZKLQ+oYZxwXmsNP+eX",
	"F2ScYVF0Fu0nw2To68sSFStFdBYdJsPksPZbL7s9Vrl87wYXNaQjqNUDGnCubzBgUQIO/t0ap4E2o3K+",
	"xRsAa4MzI0/VeFu64MsjggZMDVs8zYPh0SbBn3EBxu/gdIGj4X49BnLNcLEsJZEVWu39rR5SBIt7tH/R",
	"GWR59XdpvxPWUiLWBoTyHtEApo4B+sDeNr2Pnyhu26oomG9zhRt7mbXl1D0tyN/UeM47qQ4Ycg0jeAxk",
	"CVM36K0xx5mYowIPloBxbtDaZKQ+5AiG3fqVXi+Un5B30F6olxvAJ4oCuWCOMN9IXVGsbXKM03AIgcmg",
	"UgslGri49H9yXZlgkesqr28VvByt+17zxbMpch1333fDCYG4+w1b298B+e2m1KiqRrDBlIfPxsJ6iO/h",
	"4KK24IClPf3X386Vzn0x5UXApI9lgHfCOlsbr7Atxg6+IWNk3QFBAd6liBxDl7rtvUG9/qVAgykKX092",
	"nddXoN6yZuj6wiY5nQXma3cqicMGINRgkMN0AS9WnRh4++P1DzFQvLn+4WUyUtdV6btq4HKDCISfLLwo",
	"KlcxKUmUqaysmOPLs5ECGMB3310afUe3Wnz33RlMpJpNYphI5uhPAKYT7/RMyvrQxmHA6RmGd7DDUd/r",
	"SnGKg1N9508rhBrXJ/qP4dSC3S2f0kfmVhQyXZntBN5ixirp6OxCW+eFrCg01RKphTVSk88TeJEyiwOh",
	"LCorvFHZahowCfjpPWgFE8r2k5fgLcKihVvhct8E0JkPlW05sqmeIwW6uqEieIjQ620VrQDnaBbtbopv",
	"xfREvF+EdZfBJnyLlhXo0FifKjwu+VyhWaxgibfAKG5ZNQ9Cic4OhnFnfNzqIe9v9i3v434CdSeqTWED",
	"4/bv/NzZ9FWdcDpyiSmb6Uzv9X2bcEXl9/XtO2SXI6Jeusw9le6jQ4cO1WPSUx/FuihsE11677vm+NB2",
	"eICZ461vEbS56aNf++4zS3srpWeWby+dEHe+xY1CWHu+G33aQCXPBwlWDe6erHfJZkL50CqFdat89Afi",
	"Ei9raIXKbhamgNokTR/MQ0AbTBlVIGW4D514Hz8GnEHhbdODPt9oAkPBFjBFECqVFUcOQkmhcLOOCec1",
	"s4pd4Np6tvBt0WyL6JrN+Cb7HwdgV0sAmybCP2Q5GAyHsGAt6iV+3Psi+P1TQGR4FY7cQDgLmGUY8PVa",
	"IyK8Z5CM1F+06TgP4VCDysWwEoRvLQiVoxHNu3VhuOJXhv9LIQS13NG8m4eQ5kJy4Nq/GuYg/NcdsYYy",
	"S0bqYnloi1rKjFnARNjxkuYZkHHX/31T/y+W4JMGswVG+tDWT+gaP+zDWr43uYzi9VsIbX/qDej9I/Td",
	"x+ztvpcREP8DQ/Svv168hVo+noujb+d8QQJkXbUUOtnhJ3TAgLxT4ha32tt4X6ekamHTzX4tLYZSa4s/",
	"rfVbQiYZqfOKCwd+vORdiW5ZkdH7CaQZ+FGB96rVDLLuwy7AN5Jtn21fEpf+9p1c9c1M/fnTWv+7UE/J",
	"csNvwMN636LPAOq69J9JsJsE/y+EhKcm4V+9CukaaZ2OVb+3B8rBh4OjVUZGZ9HefD+6/3T/vwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
